import {
  processAddPayment,
  processAnnounceWinners,
  processApplication,
  processApplicationApproval,
  processApplicationCompleted,
  processApplicationLike,
  processApplicationRejection,
  processCommentActivity,
  processCommentReply,
  processCommentSponsor,
  processCommentTag,
  processCreateListing,
  processDeadlineExceeded,
  processDeadlineExceededWeek,
  processDeadlineExtended,
  processDeadlineThreeDays,
  processGrantPayment,
  processNonSTWinners,
  processPoWLike,
  processScoutInvite,
  processScoutReminder,
  processSponsorSubmissions,
  processSTWinners,
  processSubmissionLike,
  processSubmissionRejected,
  processTalentReminder,
  processTalentSubmission,
  processVerifiedStatus,
  processWeeklyRoundup,
} from '../handlers';
import { type EmailActionType } from '../types';

export const emailActionCategoryMapping = {
  // talent emails
  createListing: 'createListing',
  commentActivity: 'commentOrLikeSubmission',
  commentReply: 'replyOrTagComment',
  commentTag: 'replyOrTagComment',
  submissionLike: 'commentOrLikeSubmission',
  applicationLike: 'commentOrLikeSubmission',
  powLike: 'commentOrLikeSubmission',
  weeklyListingRoundup: 'weeklyListingRoundup',
  scoutInvite: 'scoutInvite',

  // sponsor emails
  commentSponsor: 'commentSponsor',
  submissionSponsor: 'submissionSponsor',
  application: 'submissionSponsor',
  deadlineExceeded: 'deadlineSponsor',
  deadlineExceededWeek: 'deadlineSponsor',
} as const;

export const emailTypePriority: Record<EmailActionType, number> = {
  submissionTalent: 1,
  application: 1,
  commentReply: 1,
  commentSponsor: 1,
  commentTag: 1,
  scoutInvite: 1,
  verifiedListingStatus: 1,
  scoutReminder: 2,
  submissionSponsor: 2,
  announceWinners: 2,
  STWinners: 2,
  nonSTWinners: 2,
  addPayment: 2,
  grantPaymentReceived: 2,
  commentActivity: 2,
  submissionLike: 2,
  submissionRejected: 2,
  applicationLike: 2,
  deadlineExceededWeek: 2,
  deadlineExceeded: 2,
  deadlineExtended: 2,
  grantCompleted: 2,
  grantApproved: 2,
  grantRejected: 2,
  deadline3days: 3,
  createListing: 4,
  weeklyListingRoundup: 5,
  talentReminder: 6,
  powLike: 2,
  // dupe: 1,
};

export const emailProcessors: Record<EmailActionType, any> = {
  addPayment: processAddPayment,
  announceWinners: processAnnounceWinners,
  application: processApplication,
  commentReply: processCommentReply,
  commentSponsor: processCommentSponsor,
  commentActivity: processCommentActivity,
  commentTag: processCommentTag,
  createListing: processCreateListing,
  deadline3days: processDeadlineThreeDays,
  deadlineExceeded: processDeadlineExceeded,
  deadlineExceededWeek: processDeadlineExceededWeek,
  deadlineExtended: processDeadlineExtended,
  grantApproved: processApplicationApproval,
  grantCompleted: processApplicationCompleted,
  grantPaymentReceived: processGrantPayment,
  grantRejected: processApplicationRejection,
  scoutInvite: processScoutInvite,
  scoutReminder: processScoutReminder,
  submissionLike: processSubmissionLike,
  submissionRejected: processSubmissionRejected,
  applicationLike: processApplicationLike,
  submissionSponsor: processSponsorSubmissions,
  submissionTalent: processTalentSubmission,
  STWinners: processSTWinners,
  nonSTWinners: processNonSTWinners,
  weeklyListingRoundup: processWeeklyRoundup,
  talentReminder: processTalentReminder,
  verifiedListingStatus: processVerifiedStatus,
  powLike: processPoWLike,
  // dupe: processDupe,
};
