export type EmailActionType =
  | 'addPayment'
  | 'announceWinners'
  | 'application'
  | 'commentReply'
  | 'commentSponsor'
  | 'commentSubmission'
  | 'commentTag'
  | 'createListing'
  | 'deadline3days'
  | 'deadlineExceeded'
  | 'deadlineExceededWeek'
  | 'deadlineExtended'
  | 'grantApproved'
  | 'grantPaymentReceived'
  | 'grantRejected'
  | 'rolling15Days'
  | 'rolling30Days'
  | 'rollingUnpublish'
  | 'scoutInvite'
  | 'submissionLike'
  | 'applicationLike'
  | 'submissionSponsor'
  | 'submissionTalent'
  | 'superteamWinners'
  | 'weeklyListingRoundup'
  | 'verifiedListingStatus';
// | 'dupe'
